name: Build and Test in Ubuntu

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - name: Disable the keychain credential helper
      run: git config --global credential.helper ""
    - name: Enable the local store credential helper
      run: git config --global --add credential.helper store
    - name: Add credential
      run: echo "https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com" >> ~/.git-credentials
    - name: Tell git to use https instead of ssh whenever it encounters it
      run: 'git config --global url."https://github.com/".insteadof git@github.com:'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            build-essential \
            cmake \
            colordiff \
            git \
            libdbus-glib-1-dev \
            libglib2.0-dev \
            libgtest-dev
        # Install MAVSDK from source
        git clone --recursive https://github.com/Auterion/MAVSDK.git -b develop
        cd MAVSDK
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_SHARED_LIBS=ON -Bbuild/default -H.
        sudo cmake --build build/default --target install -j`nproc --all`
        sudo ldconfig
        # Install gtest
        cd /usr/src/gtest \
                && sudo mkdir build && cd build \
                && sudo cmake .. && sudo make -j$(nproc --all) \
                && sudo find . -name \*.a -exec sudo cp {} /usr/lib \; \
                && cd .. && sudo rm -rf build
        # Install Clang formatter
        sudo apt install -y clang-format-10
    - name: Check code formatting
      run: Tools/check_code_format.sh
    - name: Build
      run: |
        cmake -Bbuild -S.
        sudo cmake --build build -j`nproc --all` -- install
    - name: Unit test
      working-directory: build
      run: make test
